version: "3"

services:
  node:
    build: .
    image: acgomes68/alpine-node:latest
    container_name: node-${APP_NAME}
    command: yarn start
    ports:
    - ${APP_PORT}:3333
    volumes:
    - .:/home/node/app
